# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Travelbumonline
email: kpetey123@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog site for people who love to travel and share thier experiences with the world
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://travelbumonline.com" # the base hostname & protocol for your site
github_username:  kpetey123

# Build settings
markdown: kramdown
